system:
  bus_id: "3-7"
  mac_address: "B8:27:EB:00:53:01"
  pickle_filename: "switch_mac.pickle"
  port: 5005

key_mapping:
  # Left stick
  w: L_UP
  s: L_DOWN
  a: L_LEFT
  d: L_RIGHT
  t: L_PRESS

  # Right stick
  up: R_UP
  down: R_DOWN
  left: R_LEFT
  right: R_RIGHT
  y: R_PRESS

  # D-Pad
  n: DPAD_UP
  v: DPAD_DOWN
  g: DPAD_LEFT
  b: DPAD_RIGHT

  # Buttons
  l: A
  k: B
  i: X
  j: Y

  # Triggers
  1: L
  2: ZL
  8: R
  9: ZR

  # System
  6: PLUS
  7: MINUS
  "]": HOME
  "[": CAPTURE
